function mintomax(min, max) { // min and max included 
  return Math.floor(Math.random() * (max - min + 1) + min)
}

function generate() {
	var cons = document.getElementById("cons").value;
	var vow = document.getElementById("vowel").value;
	var order = document.getElementById("order").value;
	var len = document.getElementById("maxwordlen").value;
	var minlen = document.getElementById("minwordlen").value;
	var woc = document.getElementById("wordcount").value;
	var consonants = cons.split(",");
	var vowels = vow.split(",");
	console.log("consonants: " + consonants);
	console.log("vowels: " + vowels);
	
	for (let m = 0; m < woc; m++) {	
		var word = "";
		var rand = mintomax(minlen,len) + 1;
		console.log("rand: " + rand);
		
		for (let l = 0; l < rand; l++) {	
			var i = 0;
			for (let j = 0; j < order.length; j++) {
				console.log("i = " + i);
				var gc = Math.floor(Math.random() * Math.round(cons.length / 2));
				var gv = Math.floor(Math.random() * Math.round(vow.length / 2));
				var chance = Math.floor(Math.random() * 2);
				console.log("consonant index: " + gc)
				console.log("vowel index: " + gv)
				if (order[i] == "C") { if (order[i + 1] == "*") { if (chance == 1) { word = word + consonants[gc]; }} else { word = word + consonants[gc]; }}
				if (order[i] == "V") { if (order[i + 1] == "*") { if (chance == 1) { word = word + vowels[gv]; }} else { word = word + vowels[gv]; }}
				i += 1;
			}
			
		}
		if (document.getElementById('automatch').checked) {
			var def = swadesh[mintomax(0,swadesh.length)];
			if (!(document.getElementById("out").value.includes(def))) { if (!(document.getElementById("out").value.includes(word))) { document.getElementById("out").value += word + "," + def + '\n'; } }
		} else { if (!(document.getElementById("out").value.includes(word))) { document.getElementById("out").value += word + '\n';}}
		console.log(word);
	}

}

var swadesh = [
"I",
"you (singular)",
"they (singular)",
"we",
"you (plural)",
"they (plural)",
"this",
"that",
"here",
"there",
"who",
"what",
"where",
"when",
"how",
"not",
"all",
"many",
"some",
"few",
"other",
"one",
"two",
"three",
"four",
"five",
"big",
"long",
"wide",
"thick",
"heavy",
"small",
"short",
"narrow",
"thin",
"woman",
"man (adult male)",
"man (human being)",
"child",
"wife",
"husband",
"mother",
"father",
"animal",
"fish",
"bird",
"dog",
"louse",
"snake",
"worm",
"tree",
"forest",
"stick",
"fruit",
"seed",
"leaf",
"root",
"bark (of a tree)",
"flower",
"grass",
"rope",
"skin",
"meat",
"blood",
"bone",
"fat (noun)",
"egg",
"horn",
"tail",
"feather",
"hair",
"head",
"ear",
"eye",
"nose",
"mouth",
"tooth",
"tongue (organ)",
"fingernail",
"foot",
"leg",
"knee",
"hand",
"wing",
"belly",
"guts",
"neck",
"back",
"breast",
"heart",
"liver",
"to drink",
"to eat",
"to bite",
"to suck",
"to spit",
"to vomit",
"to blow",
"to breathe",
"to laugh",
"to see",
"to hear",
"to know",
"to think",
"to smell",
"to fear",
"to sleep",
"to live",
"to die",
"to kill",
"to fight",
"to hunt",
"to hit",
"to cut",
"to split",
"to stab",
"to scratch",
"to dig",
"to swim",
"to fly",
"to walk",
"to come",
"to lie (as in a bed)",
"to sit",
"to stand",
"to turn (intransitive)",
"to fall",
"to give",
"to hold",
"to squeeze",
"to rub",
"to wash",
"to wipe",
"to pull",
"to push",
"to throw",
"to tie",
"to sew",
"to count",
"to say",
"to sing",
"to play",
"to float",
"to flow",
"to freeze",
"to swell",
"sun",
"moon",
"star",
"water",
"rain",
"river",
"lake",
"sea",
"salt",
"stone",
"sand",
"dust",
"earth",
"cloud",
"fog",
"sky",
"wind",
"snow",
"ice",
"smoke",
"fire",
"ash",
"to burn",
"road",
"mountain",
"red",
"green",
"yellow",
"white",
"black",
"night",
"day",
"year",
"warm",
"cold",
"full",
"new",
"old",
"good",
"bad",
"rotten",
"dirty",
"straight",
"round",
"sharp (as a knife)",
"dull (as a knife)",
"smooth",
"wet",
"dry",
"correct",
"near",
"far",
"right",
"left",
"at",
"in",
"with",
"and",
"if",
"because",
"name",
]